### ISSUE TITLE
Support for more quote characters

### ISSUE THREAD

**Issue by michele-deus** [roskakori/cutplace#113]
I have a file with a textfield using # as the quote character and as of now I can't validate it. Pandas read_csv is capable of handling it passing option quote_character='#'.

**Comment by roskakori** [comment]
It wouldn't be a big deal to support any character as quote characters.

If you need a quick workaround, go to `cutplace/data.py` and edit the following line:

```python
_VALID_QUOTE_CHARACTERS = ["\"", "\'"]
```

**Comment by michele-deus** [comment]
Thanks!

**Comment by roskakori** [comment]
I finally got around to actually implement this.

For the record, the currently supported quote characters are:
```
!"#$%&'*+-/:;=?\^_`~
```
