### ISSUE TITLE
Issue with Non-Ascii Characters

### ISSUE THREAD

**Issue by reggiegentle** [roskakori/cutplace#52]
cutplace seems to bomb out when non-ascii characters are involved in a source file.  IE, if you have an e with a tilda over it, cutplace just bombs out.  Is this as designed or could it be addressed or is there a potential work-around?

**Comment by roskakori** [comment]
With the test improvements of the past weeks, all readers in `rowio` and `validio` seem to be able to process unicode, so I consider this solved. If still something slipped through the cracks, we'll address this when it shows up.
